version: '3.7'
services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Recife
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_node_react
    ports:
      - "3309:3306"
    networks:
      - udemy-network
        
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: lucasemanoel/node-react-backend
    restart: always
    environment: 
      TZ: America/Recife
    ports:
      - "5000:5000"
    command: ./wait-for.sh db:3306 -- ./startup.sh
    depends_on:
      - db
    networks:
      - udemy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: lucasemanoel/node-react-frontend
    restart: always
    environment: 
      TZ: America/Recife
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - udemy-network

networks:
  udemy-network:

